### ISSUE TITLE
Tablet mode: "Left click threshold" too low

### ISSUE THREAD

**Issue by tnbp** [Grumbel/udraw#4]
Around line 300 in udraw-driver.cpp, the driver (in tablet mode) does this:

```
if (decoder.get_pressure() > 0) {
 evdev.send(EV_KEY, BTN_TOUCH, 1);
}
```

decoder.get_pressure(), of course, is defined in udraw_decoder.hpp as

```
int get_pressure() const
{
 return m_data[13] - 0x70;
}
```

However, my tablet does not send 0x70 when released completely, but 0x71 or 0x72, resulting in a type of "perpetually pressed left mouse button" situation. Unless it is just my device (faulty? error tolerance?), it might be a good idea to increase the "pressure" threshold above to 
`if (decoder.get_pressure() > 10)`, for example. Even on non-faulty hardware, that's still a very light touch, right?

**Comment by parkerlreed** [comment]
I think I'm noticing the same behavior. The hover in tablet mode clicks like crazy.

**Comment by tnbp** [comment]
This has been fixed as per the commit above.
